[255] reduced number of dates shown on x axis to allow for even spacing
covid-alert-ny/covid-green-app pull request #285
Opened 2020-09-03 11:02 UTC by JohnAGill

This reduces the number of dates shown from 6 to 5 so that the spacing between them is always consistent

2020-09-03 15:21 UTC, ShaunBaker requested changes
I dont think this is a valid fix.

Desired data is to show the past week and just dropping a day is not sufficient.

2020-09-03 16:22 UTC, AlanSl commented
@ShaunBaker in NY now it's 30 days of data not one week.

Also, there's a remaining bug on the server side that is giving us 29 days of data instead of 30 which is part of the reason the last date looks so off.

2020-09-03 16:45 UTC, AlanSl commented
I like how the current fix applied by @JohnAGill looks currently - but unfortunately it's going to break as soon as we actually get 30 days of data. There will be two labels clashing at the end like this:

<img width=300 src="https://user-images.githubusercontent.com/29628323/92143417-2b7fc200-ee0d-11ea-817f-ba702bfb86b1.jpg" />

30 days of data: `6` looks best. 29 days of data: `7` looks best. And we have no idea when the 30 day fix is finally going to come through. 

It's not a great situation.

@JohnAGill can you maybe make it conditional, for example take it out of props and set the value to `6` if `axisData.length` is 29 and otherwise `6` as it was before. Also add a comment explaining what's going on because it'll look odd that something like that is hardcoded but I think it's the best we can do.

The alternative is import `d3.ticks` and let it figure it out, but it's quirky.

2020-09-07 16:28 UTC, AlanSl commented on src/components/molecules/bar-chart.tsx
> +  const intervalsCount = axisData.length > 30 ? 7 : 6;
```suggestion
  const intervalsCount = axisData.length < 30 ? 7 : 6;
```
Issue is with 29 and 30, not 30 and 31

2020-09-07 16:47 UTC, AlanSl approved these changes

2020-09-07 16:49 UTC, AlanSl commented
I've fixed the direction of the `<` and the merge conflict so we can get it in.

Antoine's got a new design for the x axis here anyway so this'll just be a temporary thing to stop the x-axis looking broken while we're still stuck with just 29 days of data.

2020-09-08 08:35 UTC, floridemai approved these changes

2020-09-08 08:35 UTC, merged