Accessible Markdown links - proof of concept
covid-alert-ny/covid-green-app pull request #328
Opened 2020-09-04 17:03 UTC by AlanSl

Tested on Android, not yet on iOS. 

On Android this:

 - Splits the link out into a focus-able section if it's in a block of text and the screen reader is active
 - Has the screen reader read the text of the link first, then a hint which is either the `title` from Markdown if there is one or a translated default if there isn't (e.g. "Open web page", "Call telephone number"), then the role, "link".

So typical UX is like:

> 1-202-002-200; call telephone number; link
> Find sites in your area; open web page; link

Titles for accessibility can be specified in Markdown if needed like `[text](http://site.com "This is the title")`

@floridemai can you point me towards issues relating to markdown accessibility so I can see what other features we need?

2020-09-04 17:59 UTC, floridemai commented
@AlanSl Nice one. Here is the list of issue:
https://github.com/project-vagabond/covid-green-app/issues/265
https://github.com/project-vagabond/covid-green-app/issues/264
https://github.com/project-vagabond/covid-green-app/issues/248
https://github.com/project-vagabond/covid-green-app/issues/246
https://github.com/project-vagabond/covid-green-app/issues/237
https://github.com/project-vagabond/covid-green-app/issues/224

Links - should have a "button" role when the navigate inside the app and should have the "link" role when an external website is opened. No need to "open web page" having a role of link implies that.
I'm not sure about the phone, do add a comment in the issue and ask @willslone or @jonnyjames what's the best way of achieving it.
Also, do check the translation file for other link and make sure they're working?
I'll test on iOS myself when the PR is ready.

2020-09-07 13:59 UTC, AlanSl commented
- [x] Identifying links as links - https://github.com/project-vagabond/covid-green-app/issues/265
- [x] Making inline links reachable:
  - [x] tel - https://github.com/project-vagabond/covid-green-app/issues/264 and https://github.com/project-vagabond/covid-green-app/issues/246
  - [x] http - https://github.com/project-vagabond/covid-green-app/issues/248 and https://github.com/project-vagabond/covid-green-app/issues/237 and https://github.com/project-vagabond/covid-green-app/issues/224

2020-09-07 14:02 UTC, AlanSl commented
@floridemai I've made changes based on your comment and checked the 6 linked issues, this should cover all of them now

2020-09-07 14:33 UTC, floridemai requested changes
Before:
<img width="400" src="https://user-images.githubusercontent.com/1158133/92397757-0acaab80-f130-11ea-8679-d4d7cf87a2b2.PNG" />

After:
<img width="400" src="https://user-images.githubusercontent.com/1158133/92397765-0e5e3280-f130-11ea-957d-521883f47e4c.PNG" />

2020-09-07 15:35 UTC, AlanSl commented
@floridemai I've pushed a fix for that being styled like that without screen reader being on.

On Android, it's necessary to split links out from body text like that when using voice assistant else they aren't focusable. Latest commit makes that layout change android-only as well as screen-reader-only. Are the links accessible for you in the latest commit?

I'm looking to see if it's possible to reduce the visual changes but it might not be without other side effects.

2020-09-07 16:20 UTC, AlanSl commented
We can fix the space in the layout... but only by setting `margin-bottom: -16` on Markdown default `text` style. It doesn't appear to have side effects outside of this case because everywhere else, `<Text>` elements are either not used for layout or overridden - however, the potential for causing bad display glitches seems too high for the small gain given that it only looks like this when screen readers are enabled (and, in that one case, is more accessible).

The extra space seems to be some quirk of `<Text>` nesting that isn't directly controllable - it's still there with 0 margins and padding and is unrelated to `justifyContent` on the text or the block parent:

![Screenshot_20200907-171739_COVID Alert NY](https://user-images.githubusercontent.com/29628323/92405835-67c56200-f12e-11ea-8581-a9c40db2afba.jpg)

2020-09-08 14:00 UTC, floridemai approved these changes

2020-09-08 14:00 UTC, merged