Chore/county dd search icon
covid-alert-ny/covid-green-app pull request #358
Opened 2020-09-08 14:46 UTC by ckiss

added the search icon that is always visible when you open the county dd
https://github.com/project-vagabond/covid-green-app/issues/239
https://github.com/project-vagabond/covid-green-app/issues/303

[
![Screenshot_20200908_142741_gov ny health proximity](https://user-images.githubusercontent.com/1004239/92491670-2949a900-f1fb-11ea-87cf-cad4f731b7d5.jpg)
](url)

2020-09-08 15:11 UTC, floridemai requested changes
@ckiss And where are the a11y features for it? (which was the sole purpose of having it)

2020-09-08 15:47 UTC, ckiss commented
@floridemai my understanding was that the a11y issues were fixed and it was just missing a permanently visible search icon. What are the a11y features that are missing?

2020-09-08 15:55 UTC, floridemai commented
> @floridemai my understanding was that the a11y issues were fixed and it was just missing a permanently visible search icon. What are the a11y features that are missing?

https://github.com/project-vagabond/covid-green-app/pull/358#issuecomment-688967720

2020-09-09 15:04 UTC, AlanSl approved these changes

2020-09-09 15:05 UTC, merged