Fix/448 loading screen size
covid-alert-ny/covid-green-app pull request #454
Opened 2020-09-16 13:25 UTC by JohnAGill

issue: [#448](https://github.com/project-vagabond/covid-green-app/issues/448)

2020-09-16 13:39 UTC, floridemai commented
@JohnAGill Instead of doing all this shenanigans should we use an png for the DOH logo? Actually "re-use" them from here:  https://github.com/project-vagabond/covid-green-app/tree/nys/ios/Assets.xcassets/StateLogo.imageset

2020-09-17 13:11 UTC, AlanSl approved these changes
Can you please remove the commented out section? We've got it in git history and this PR if we need to go back to it.

After that, LGTM, works on different size devices in the simulator

2020-09-17 13:12 UTC, AlanSl commented on src/components/views/loading.tsx
> +        />*/}
Please remove this before merge as above

2020-09-17 13:13 UTC, AlanSl commented on src/components/views/loading.tsx
> +import {StyleSheet, View, Platform, Image} from 'react-native';
Check lint - isn't `Platform` unused now?

2020-09-17 13:22 UTC, AlanSl commented
@floridemai FYI the PNG doesn't look great on large high-res Android devices (e.g. this is on a Note 8); but if the PNG is necessary to avoid changes on iOS, that's probably more important.

![Screenshot_20200918-142003_COVID Alert NY](https://user-images.githubusercontent.com/29628323/93475943-203e9300-f8f1-11ea-8612-aff0bbdb9784.jpg)

2020-09-17 13:30 UTC, AlanSl requested changes
Putting this in build 43 so don't merge until build 42 is done (and comments, unused variables etc are cleaned up)

2020-09-17 13:34 UTC, floridemai commented
> @floridemai FYI the PNG doesn't look great on large high-res Android devices (e.g. this is on a Note 8, open the image full size and you'll see it's slightly blurry and looks a bit small on the screen but it's not a major issue); but if the PNG is necessary to avoid changes on iOS, that's probably more important.

Did you try 1x 2x 3x version (something like https://github.com/project-vagabond/covid-green-app/tree/nys/src/assets/images/callback) as that should work just fine and I think is the exact same way iOS does it on launch s screen (see my prev post). https://reactnative.dev/docs/images
TBH Now i'm wondering what happens with the svgs we use on different screens. share button for example. I think it remains the same everywhere.

We did the width trick for images to cover the entire screen here and there but i'm not sure we can say for sure that will match all launch screens on all devices.

Anyway, feel free to merge if you tested on a couple of them and works ;)

2020-09-17 13:35 UTC, floridemai commented
@AlanSl @JohnAGill Ups, I just was that John updated to using PNG. Do you mind asking @helloantoine to provide you 1x 2x 3x versions?

2020-09-17 13:56 UTC, JohnAGill commented
Made the above changes and added 2x and 3x images. Also adjusted the logo on the ios splash screen as it didn't match the android version

2020-09-17 14:15 UTC, AlanSl approved these changes
Code is clean, looks good on high-res Android, seems to still be fine on iOS simulator, I'm happy

![Screenshot_20200917-151152_COVID Alert NY](https://user-images.githubusercontent.com/29628323/93483281-9397d300-f8f8-11ea-98cc-779c33ba8473.jpg)

2020-09-17 14:25 UTC, merged